### ISSUE TITLE
Use granito.io domain

### ISSUE THREAD

**Issue by ayashkov** [granito-source/ngx-hal-client#10]
Use `granito.io` domain to host the documentation of the organization.

### Tasks

- [x] Delegate the domain.
- [x] Add `granito.io` and `www.granito.io` addresses.
- [x] Verify the domain in GitHub.
- [x] Configure the domain to host the documentation.
