### ISSUE TITLE
Provide convenience functions for RxJS and more

### ISSUE THREAD

**Issue by ayashkov** [granito-source/ngx-hal-client#13]
As a _Developer_ I want the library to provide convenience operators for RxJS that wrap common HAL operations (`follow()`, `read()`, etc.), so that the resulting code would be more readable.

### Acceptance criteria

Confirm that:

* there is an `objectFrom()` function that converts any resource or array of resources to an object (and array is an object too) that lacks any HAL-specific properties: `_links`, `_embedded`, `_client`;
* there is a `completeWith()` operator that completes the observable at the same time as the parameter observable;
* there is a `follow()` operator that is equivalent of using `follow()` method on a `Resource`;
* there is a `create()` operator that is equivalent of using `create()` method on a `HalBase`;
* there is a `read()` operator that is equivalent of using `read()` method on an `Accessor`;
* there is a `readCollection()` operator that is equivalent of using `readCollection()` method on an `Accessor`;
* there is a `refresh()` operator that is equivalent of using `read()` method on a `Resource`;
* there is a `update()` operator that is equivalent of using `update()` method on a `Resource`;
* there is a `del()` operator that is equivalent of using `delete()` method on a `HalBase`.

### Tasks

- [x] Create `objectFrom()` function.
- [x] Create `completeWith()` operator.
- [x] Create `follow()` operator.
- [x] Create `create()` operator.
- [x] Create `read()` operator.
- [x] Create `readCollection()` operator.
- [x] Create `refresh()` operator.
- [x] Create `update()` operator.
- [x] Create `del()` operator.
- [x] Update usage documentation with operators.
