### ISSUE TITLE
Basic usage documentation

### ISSUE THREAD

**Issue by ayashkov** [granito-source/ngx-hal-client#4]
As a _Library User_ I want to have at least some basic library description with examples, so that I could start using the library right away.

### Acceptance criteria

Confirm that the project contains enough information for a developer to start using the library, in particular:

* how to add it to an Angular project;
* how to read the root of the API;
* how to create, read/refresh, update, delete resources;
* how to use collections.

### Tasks

- [x] Update `README.md` with the usage information.
- [x] Update for the changes introduced by story #5.
- [x] Add API documentation.
