### ISSUE TITLE
Separate following the link and acting on the link in the API

### ISSUE THREAD

**Issue by ayashkov** [granito-source/ngx-hal-client#5]
As a _Library User_ I want the operations to follow the link and operating on `'self'` to be separate, so that I could only execute operations on the links that exist in the resource.

### Acceptance criteria

Confirm that:

* `Resource` has `follow(rel: string, params: Params = {}): Linked | undefined` method;
* calling the method returns `Linked` object if the relation exists and `undefined` otherwise;
* the method expands parameters for templated links;
* `Accessor` object defines the following methods:
    * `create(obj: Object): Observable<Accessor>` — create a new resource using the identity provided by the object;
    * `read(type: type: Type<T>): Observable<T>` — read the resource identified by the object;
* `Resource` object defines the following methods:
    * `create(obj: Object): Observable<Accessor>` — create a new resource using the identity provided by the object (to be used with collections);
    * `read(): Observable<this>` — refresh the resource;
    * `update(): Observable<Accessor>` — update the resource;
    * `delete(): Observable<void>` — delete the resource.

### Tasks

- [x] Introduce `follow()` method and `Linked` class.
- [x] Limit all `Resource` operations to `'self'` relation.
- [x] Unit test coverage to the max.
