### ISSUE TITLE
Pre-checks for operations on accessors and resources

### ISSUE THREAD

**Issue by ayashkov** [granito-source/ngx-hal-client#8]
As a _Library User_ I want to have a way to check if certain operation is allowed without executing it, so that I can make decisions affecting the UI based on this information.

### Acceptance criteria

Confirm that:

* when `self` link does not have `methods` array defined the `canCreate`, `canRead`, `canUpdate` and `canDelete` are all `true`;
* when `self` link has `methods` array, then the properties:
    * `canCreate` is `true` when `POST` is in the array and `false` otherwise;
    * `canRead` is `true` when `GET` is in the array and `false` otherwise;
    * `canUpdate` is `true` when `PUT` is in the array and `false` otherwise;
    * `canDelete` is `true` when `DELETE` is in the array and `false` otherwise;
* method names are compared in the case insensitive way;
* accessors received from `follow()` preserve `methods` array;
* accessors received from `update()` preserve `methods` array.

### Example

If we have a resource like this:

```json
{
  "_links": {
    "orders": {
      "href": "/api/v1/orders",
      "methods": ["GET", "POST"]
    },
    "items": {
      "href": "/api/v1/items"
    }
  }
}
```

then

```ts
resource.follow('missing')?.canRead === undefined;

resource.follow('orders')?.canCreate === true;
resource.follow('orders')?.canDelete === false;

resource.follow('items')?.canCreate === true;
resource.follow('items')?.canDelete === true;
```

### Tasks

- [x] Implement `canCreate` property.
- [x] Implement `canRead` property.
- [x] Implement `canUpdate` property.
- [x] Implement `canDelete` property.
- [x] Ensure `follow()` preserves `methods` array.
